In [1]:
import tensorflow as tf

In [2]:
#placeholder的使用，必须定义类型而且类型必须一致
data1 = tf.placeholder(tf.float16)
data2 = tf.placeholder(tf.float16)
dataAdd = tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd,feed_dict={data1:2,data2:3}))

5.0


In [3]:
m1 = tf.constant([[2,3]]) #一行两列数组

In [4]:
print(m1.shape)

(1, 2)


In [5]:
m2 = tf.constant([
                            [1,2,3],
                            [4,5,6]
                        ])
#两行三列矩阵

In [6]:
print(m2.shape)

(2, 3)


In [7]:
with tf.Session() as sess:
    print('second session')
    print(sess.run(m2[0]))
    print(sess.run(m2[:,1]))

second session
[1 2 3]
[2 5]


In [8]:
mat0 = tf.zeros([2,3],dtype=tf.float16)

In [15]:
mat1 = tf.ones([2,3],dtype=tf.int16)

In [16]:
mat2 = tf.fill([2,3],15.0)

In [20]:
mat3 = tf.zeros_like(mat2)

In [24]:
mat4 = tf.linspace(0.0,2.0,11)
mat5 = tf.random_uniform([2,3],-1,2)

In [25]:
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))
    print(sess.run(mat5))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[1 1 1]
 [1 1 1]]
[[ 15.  15.  15.]
 [ 15.  15.  15.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[ 0.          0.2         0.40000001  0.60000002  0.80000001  1.
  1.20000005  1.39999998  1.60000002  1.80000007  2.        ]
[[-0.17461205 -0.23443174  1.15608501]
 [ 1.14100409  0.50867355  1.92116022]]


In [26]:
import numpy as np

In [33]:
n1 = np.ones([2,3])
n2 = n1 + 1

In [34]:
print(n1)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [35]:
print(n2)

[[ 2.  2.  2.]
 [ 2.  2.  2.]]


In [36]:
print(n1* n2)

[[ 2.  2.  2.]
 [ 2.  2.  2.]]


In [37]:
print(n1+n2)

[[ 3.  3.  3.]
 [ 3.  3.  3.]]
